#! /bin/sh

#bspc config border_width	2
#bspc config window_gap		8

bspc config border_width	1
bspc config window_gap		8

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 1
bspc config focus_follows_pointer true

bspc monitor LVDS1 -d web term chat code music
bspc monitor VGA1 -d ext1 ext2 ext3 ext4 ext5

bspc config normal_border_color '#282828'
bspc config focused_border_color '#7cafc2'
#bspc config presel_border_color '#3030ee'
bspc config presel_feedback_color '#444445'
bspc config normal_sticky_border_color '#1d2021'
bspc config focused_sticky_border_color '#d5c4a1'
bspc config urgent_border_color '#c50000'

bspc rule -a firefox border=off state=tiled
bspc rule -a URxvt state=tiled
bspc rule -a mpv state=tiled
bspc rule -a pavucontrol-qt state=tiled


# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
#if [ -x $HOME/bin/bspwm_laptop_external_monitor ];then
#    bspwm_laptop_external_monitor
#fi

xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
dunst &
xmodmap ~/.Xmodmap &
setxkbmap -option 'caps:ctrl_modifier' -layout pl &
#xcape -e 'Caps_Lock=Escape' &
feh --bg-scale /home/gonz/etc/.config/wallpaper/tapetka.jpg &
notify-send "Welcome to the Void, gonz"
compton -f &
#polybar top &

if [ -x /usr/bin/polybar ]; then
    bash $HOME/.config/polybar/launch.sh
fi

mpd &
/home/gonz/bin/devmon-d &
sxhkd &
